name: Secrets and Env Variables

on: push

jobs:
  api-secret:
    name: Env Instantiation 
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        env: # Or as an environment variable
          API_KEY: ${{ secrets.API_KEY }}
  
      - name: Test
        run: echo "TEST LINE"
